package main

var QUOTES = []string{
	"Don't walk behind me; I may not lead. Don't walk in front of me; I may not follow. Just walk beside me and be my friend.",
	"In the depth of winter I finally learned that there was in me an invincible summer.",
	"Nothing is more despicable than respect based on fear.",
	"Nothing is more despicable than respect based on fear.",
	"Nothing is more despicable than respect based on fear.",
	"You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.",
	"Autumn is a second spring when every leaf is a flower.",
	"Autumn is a second spring when every leaf is a flower.",
	"Autumn is a second spring when every leaf is a flower.",
	"Autumn is a second spring when every leaf is a flower.",
	"But what is happiness except the simple harmony between a man and the life he leads?",
	"You cannot create experience. You must undergo it.",
	"There is no love of life without despair of life.",
	"There is no love of life without despair of life.",
	"There is no love of life without despair of life.",
	"There is no love of life without despair of life.",
	"Nothing is more despicable than respect based on fear.",
	"Nothing is more despicable than respect based on fear.",
	"Charm is a way of getting the answer yes without asking a clear question.",
	"Do not wait for the last judgment. It comes every day.",
	"Do not wait for the last judgment. It comes every day.",
	"Do not wait for the last judgment. It comes every day.",
	"Too many have dispensed with generosity in order to practice charity.",
	"But in the end one needs more courage to live than to kill himself.",
	"But in the end one needs more courage to live than to kill himself.",
	"But in the end one needs more courage to live than to kill himself.",
	"But in the end one needs more courage to live than to kill himself.",
	"But in the end one needs more courage to live than to kill himself.",
	"It is natural to give a clear view of the world after accepting the idea that it must be clear.",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Should I kill myself, or have a cup of coffee?",
	"Fiction is the lie through which we tell the truth.",
	"Fiction is the lie through which we tell the truth.",
	"Live to the point of tears.",
	"Live to the point of tears.",
	"Live to the point of tears.",
	"Always go too far, because that's where you'll find the truth.",
	"Always go too far, because that's where you'll find the truth.",
	"Always go too far, because that's where you'll find the truth.",
	"When the soul suffers too much, it develops a taste for misfortune.",
	"When the soul suffers too much, it develops a taste for misfortune.",
	"Yeeeeeeeeh!",
	"κολοκυθοκεφτέδες",
}
